name: PR Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Request PR review
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.requestReviewers({
              pull_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              reviewers: ['octocat']
            })
            git config --global credential.helper wincred
            git add .
            git commit -m "작업 내용 반영"
            git push origin main 